services:
  postgres:
    image: postgres:17.4
    container_name: airtickets
    restart: no
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  server:
#    container_name: app
#    env_file:
#      - .env
#    build: .
#    restart: no
#    ports:
#      - "8081:8080"
