version: '3.9'

x-container: &container
  logging:
    options:
      max-size: "200k"
      max-file: "10"
services:
  db:
    <<: *container
    image: postgres
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: no
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_ROOT_PASSWORD: root
      PGPORT: 5430
    volumes:
      - ./volumes/postgres:/var/lib/postgres
    ports:
      - "5431:5430"
