services:
  postgres:
    image: postgres:17.4
    container_name: airtickets
    restart: no
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      retries: 3
      start_period: 0s
      timeout: 0s
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  liquibase:
    image: liquibase/liquibase:4.31
    container_name: liquibase
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - ./migrations/db:/liquibase/db
    command:
      [
        "--url=jdbc:postgresql://postgres:5432/${DB_NAME}",
        "--changeLogFile=db/changelog/db.changelog-master.yaml",
        "--username=${DB_USER}",
        "--password=${DB_PASS}",
        "--logLevel=info",
        "update"
      ]
  elasticsearch:
    image: elasticsearch:9.0.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.authc.apiKey.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/ssl/new_cert.p12
      - xpack.security.http.ssl.truststore.path=/usr/share/elasticsearch/config/ssl/new_cert.p12
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/ssl/new_cert.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/ssl/new_cert.p12
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASS}
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
      - ./volumes/es_ssl:/usr/share/elasticsearch/config/ssl
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:9.0.1
    container_name: kibana
    environment:
      - elasticsearch.username=${ELASTICSEARCH_USERNAME}
      - elasticsearch.password=${ELASTICSEARCH_PASS}
      - elasticsearch.hosts=${ELASTICSEARCH_URL_INTR}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch