spring:
    application:
        name: airlines
    config:
        import: optional:file:.env[.properties]
    datasource:

        url: jdbc:postgresql://localhost:5431/airlinesDB
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        generate-ddl: true
        show-sql: true

ngrok:
    enabled: false

server:
    port: 8080





