spring:
    docker:
        compose:
            file: docker-compose.yml
            lifecycle-management: start_only
            skip:
                in-tests: true
    config:
        import: file:.env[.properties]
#    datasource:
#        url: jdbc:postgresql://localhost:5432/${DB_NAME}
#        username: ${DB_USER}
#        password: ${DB_PASS}
#        driver-class-name: org.postgresql.Driver
#    jpa:
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
#        hibernate:
#            ddl-auto: create
#        generate-ddl: true
#        show-sql: true

server:
    port: 8081
